server:
  port: 9000

spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
dubbo: 
  scan:
    basePackages: com.jt
  application:
    name: provider-user   #提供者服务名称
  registry:
    address: zookeeper://192.168.161.129:2181?backup=192.168.161.129:2182,192.168.161.129:2183
  protocol:  
    name: dubbo
    port: 20880     #zookeeper服务通信端口 消费者连接提供者端口

      
mybatis-plus:
  type-aliases-package: com.jt.dubbo.pojo       #配置别名包路径
  mapper-locations: classpath:/mybatis/mappers/*.xml  #添加mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                #开启驼峰映射规则